sudo required

services:
  - docker

before_install:
  - docker build -t grabyourfreedom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run grabyourfreedom/react-test npm test -- --coverage

after_success:
  - docker build -t grabyourfreedom/multi-client ./client
  - docker build -t grabyourfreedom/multi-nginx ./nginx
  - docker build -t grabyourfreedom/multi-server ./server
  - docker build -t grabyourfreedom/multi-worker ./worker

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push rabyourfreedom/multi-client
  - docker push rabyourfreedom/multi-nginx
  - docker push rabyourfreedom/multi-server
  - docker push rabyourfreedom/multi-worker