sudo: required

services:
  - docker

before_install:
  - docker build -t grabyourfreedom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run grabyourfreedom/react-test npm test -- --coverage

after_success:
  - docker build -t grabyourfreedom/multi-client ./client
  - docker build -t grabyourfreedom/multi-nginx ./nginx
  - docker build -t grabyourfreedom/multi-server ./server
  - docker build -t grabyourfreedom/multi-worker ./worker

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push grabyourfreedom/multi-client
  - docker push grabyourfreedom/multi-nginx
  - docker push grabyourfreedom/multi-server
  - docker push grabyourfreedom/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-793820337215
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY